server:
  port: 8030
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos

        password: nacos
        namespace: public
stock-service:
  ribbon:
    NFLoadBanlancerRUleClassName: com.ribbon.rule.CustomRule
ribbon:
# 开启ribbon饥饿加载
  eager-load:
    #配置mall-user使用ribbon饥饿加载，多个使用逗号分隔
    enabled: true
    clients: stock-service

