server:
  port: 8040
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
#springboot默认的日志级别是info，feign的debug日志界别就不会输入
#全局日志
logging:
  level:
    com.order.feign: debug
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
        contract: feign.Contract.Default #设置为默认的契约（在接口那里必须还原成员生注解）
#        连接超时时间，默认2秒
        connectTimeout: 5000
#        请求处理超时时间，默认5秒
        readTimeout: 10000
        requestInterceptors[0]:
          com.order.interceptor.feign.CustomFeignInterceptor

